name: Git Pull on Self-Hosted Runner
on:
  push:
    branches:
      - main

jobs:
  git-pull:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Git Pull
        run: |
          cd /shared/assets/
          git clone https://github.com/owen97779/Pachamama-Dashboard.git
