name: Git Pull on Self-Hosted Runner
on:
  push:
    branches:
      - main

jobs:
  git-pull:
    runs-on: homer-runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Git Pull
        run: |
          cd /shared/assets/
          git pull
